// Curated cross-category suggestions for vehicles and equipment commonly
// shipped in the US. Alphabetized for browsing. This is intentionally not an
// enum: the quote field remains free text so an unlisted make is still valid.
export const VEHICLE_MAKES: readonly string[] = [
  'Acura',
  'Alfa Romeo',
  'AMC',
  'Aprilia',
  'Arctic Cat',
  'Aston Martin',
  'Audi',
  'Autocar',
  'Bentley',
  'BMW',
  'Bobcat',
  'Buell',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Can-Am',
  'Case',
  'Case IH',
  'Caterpillar',
  'CFMoto',
  'Checker',
  'Chevrolet',
  'Chrysler',
  'Claas',
  'Daewoo',
  'DeLorean',
  'DeSoto',
  'Develon',
  'Dodge',
  'Ducati',
  'Eagle',
  'Edsel',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'Freightliner',
  'Genesis',
  'Geo',
  'GMC',
  'Harley-Davidson',
  'Hino',
  'Hitachi',
  'Honda',
  'Hudson',
  'Hummer',
  'Husqvarna',
  'Hyundai',
  'Indian Motorcycle',
  'Ineos',
  'Infiniti',
  'International',
  'Isuzu',
  'Jaguar',
  'JCB',
  'Jeep',
  'JLG',
  'John Deere',
  'Kaiser',
  'Kawasaki',
  'Kenworth',
  'Kia',
  'Komatsu',
  'KTM',
  'Kubota',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Liebherr',
  'Lincoln',
  'Lotus',
  'Lucid',
  'Mack',
  'Mahindra',
  'Maserati',
  'Massey Ferguson',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mercury',
  'Mini',
  'Mitsubishi',
  'Moto Guzzi',
  'Nash',
  'New Holland',
  'Nissan',
  'Oldsmobile',
  'Packard',
  'Peterbilt',
  'Plymouth',
  'Polaris',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Ram',
  'Rivian',
  'Rolls-Royce',
  'Royal Enfield',
  'Saab',
  'Sany',
  'Saturn',
  'Scion',
  'Smart',
  'Sterling',
  'Studebaker',
  'Subaru',
  'Suzuki',
  'Takeuchi',
  'Terex',
  'Tesla',
  'Toyota',
  'Triumph',
  'Victory',
  'VinFast',
  'Volkswagen',
  'Volvo',
  'Western Star',
  'Willys',
  'Yamaha',
  'Yanmar',
  'Zero Motorcycles',
];
